# Links

- [Liu 2025: Cell type–specific 3D-genome organization and transcription regulation in the brain](https://www.science.org/doi/10.1126/sciadv.adv2067)
- [GitHub repo for Liu 2025](https://github.com/ZhuangLab/Chromatin_Analysis_MOp/)

# Processing FOF-CT files

## Docs

- [Docs: 4DN FISH Omics Format - Chromatin Tracing (FOF-CT)](https://fish-omics-format.readthedocs.io/en/latest/)
- [DNA-Spot/Trace Data core table](https://fish-omics-format.readthedocs.io/en/latest/core.html)
- [Cell Data table](https://fish-omics-format.readthedocs.io/en/latest/cell.html)

Note: FOV = 'fields of view'

## Examining files

### Examining DNA-Spot/Trace Data core table

In [16]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# # ==== Examine header info

# Number of header lines
echo $(grep '^["#]' dna_spot_trace_core.csv | wc -l)" header lines, including col labels"
echo $(grep ',,,' dna_spot_trace_core.csv | wc -l)" header lines, excluding col labels"

# Column labels
echo -e "\nColumn labels:"
grep -v ',,,' dna_spot_trace_core.csv | head -n 1 | sed 's/.*(//;s/).*//' | tr ',' '\n' | awk 'BEGIN{c=1}{print c "\t" $0; c += 1}'

# Column label desc
echo -e "\nColumn label desc:"
grep ',,,' dna_spot_trace_core.csv | tail -n 7 | sed 's/,,*//g'

23 header lines, including col labels
22 header lines, excluding col labels

Column labels:
1	Spot_ID
2	Trace_ID
3	X
4	Y
5	Z
6	Chrom
7	Chrom_Start
8	Chrom_End
9	Chrom_order
10	Cell_ID
11	FOV_ID
12	CellID_byFOV
13	RNA_experiment_ID
14	DNA_experiment_ID
15	Sample_ID

Column label desc:
##XYZ_unit=nm
#Spot_ID:unique DNA spot identifier across 4dn_FOF-CT_core and 4dn_FOF-CT_demultiplxeing for the same replicate
#Trace_ID:number format as fovXX_cellXX_chrXX_chromatidXX
#Chrom_order:order of DNA region on its respective chromosome
#Cell_ID:unique cell identifier across the datatables
#FOV:FOV ID across datatables for the same replicate
#CellID_byFOVspecific cell identifier relative to the FOV

In [9]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# ==== Check uniqueness of cells
echo -e "Uniqueness of cells"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 10-12 | sort | uniq | wc -l)" unique combos of 'Cell_ID, FOV_ID, CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 10 | sort | uniq | wc -l)" unique 'Cell_ID'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 11-12 | sort | uniq | wc -l)" unique combos of 'FOV_ID, CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 12 | sort | uniq | wc -l)" unique 'CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 11 | sort | uniq | wc -l)" unique 'FOV_ID'"


# ==== Check uniqueness of rows
echo -e "\nUniqueness of rows"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | wc -l)" unique 'rows'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 1 | sort | uniq | wc -l)" unique 'Spot_ID'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 2,9 | sort | uniq | wc -l)" unique combos of 'Trace_ID, Chrom_order'"

Uniqueness of cells
12725 unique combos of 'Cell_ID, FOV_ID, CellID_byFOV'
12725 unique 'Cell_ID'
12725 unique combos of 'FOV_ID, CellID_byFOV'
253 unique 'CellID_byFOV'
148 unique 'FOV_ID'

Uniqueness of rows
8258329 unique 'rows'
8258329 unique 'Spot_ID'
8258329 unique combos of 'Trace_ID, Chrom_order'

In [11]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# ==== Check that the chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column
ndiff=$(awk -F '[,_]' '{ if ($1 !~ /^[#"]/){ gsub(/chr/, "", $9); if ($4 != $9) { print $4 "\t" $9 } } }' dna_spot_trace_core.csv | wc -l)
if [[ $ndiff -eq 0 ]]; then
    echo "✓ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column"
else
    echo "✗ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) does NOT correspond to the 'Chrom' column for $ndiff lines"
fi


# ==== Examine size of each region
echo -e "\nSize of each region: (1st 10 lines)"
awk -F ',' '{ if ($1 !~ /^[#"]/){ print $8 - $7 } }' dna_spot_trace_core.csv | head

✓ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column

Size of each region: (1st 10 lines)
8595
8623
11242
10504
8112
9570
8405
7269
8405
7187

### Examining Cell Data table

In [55]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# # ==== Examine header info

# Number of header lines
echo $(grep '^["#]' cell_data.csv | wc -l)" header lines, including col labels"
echo $(grep ',,,' cell_data.csv | wc -l)" header lines, excluding col labels"

# Column labels
ncols_gene=$( grep -v ',,,' cell_data.csv | head -n 1 | sed 's/.*neuron_identity,//' | tr ',' '\n' | wc -l )
echo -e "\nColumn labels (excluding $ncols_gene gene xp columns):"
grep -v ',,,' cell_data.csv | head -n 1 | sed 's/neuron_identity,.*/neuron_identity/;s/.*(//;s/).*//' | tr ',' '\n' | awk 'BEGIN{c=1}{print c "\t" $0; c += 1}'

# Column label desc
echo -e "\nColumn label desc:"
grep ',,,' cell_data.csv | tail -n 7 | sed 's/,,*//g'

23 header lines, including col labels
22 header lines, excluding col labels

Column labels (excluding 242 gene xp columns):
1	Cell_ID
2	FOV_ID
3	cell_volume_from_merlin
4	cell_center_x_global
5	cell_center_y_global
6	RNA_experiment_ID
7	Sample_ID
8	cluster_subclass
9	cluster_class
10	neuron_identity

Column label desc:
##XYZ_unit=micron
#Cell_ID:unique cell identifier across the datatables
#cell_center_x_global:x coordinate of the cell relative to all cells for the experiment replicate
#cell_center_y_global:y coordinate of the cell relative to all cells for the experiment replicate
#cluster_subclass:transcriptionally defined cell cluster lable at subclass level
#cluster_class:transcriptionally defined cell cluster lable at a higer level
"#RNA count for gene A:decoded raw RNA count for gene A (e.g. gene 1700022I11Rik)"

In [116]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
biorep="$sample_dir/biorep1_techrep1"

# # ==== Count cells & clusters

# Number of cells
echo -e $(grep -v '^["#]' "$biorep/cell_data.csv" | wc -l)" cells (lines)"

# Number of clusters
nclust_sub=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 8 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_sub" | wc -l)" clusters (only via 'cluster_subclass')"
nclust=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 8-10 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e $(echo -e "$nclust" | wc -l)" clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):"
echo -e "$nclust"

# Number of clusters (only via cluster_class)
nclust_class=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 9 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_class" | wc -l)" clusters (only via 'cluster_class')"
echo -e "$nclust_class"

17856 cells (lines)

22 clusters (only via 'cluster_subclass')
22 clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):
2184	L2/3IT,Gluta,Neuronal
1803	Astro,Astro,Non-Neuronal
1741	L6CT,Gluta,Neuronal
1474	L5IT,Gluta,Neuronal
1294	other,other,other
1088	L5ET,Gluta,Neuronal
1039	Endo,Endo,Non-Neuronal
1029	L4/5IT,Gluta,Neuronal
1029	OPC,Oligo,Non-Neuronal
972	Oligo,Oligo,Non-Neuronal
789	L6IT,Gluta,Neuronal
711	Micro,Micro,Non-Neuronal
549	Pvalb,GABA,Neuronal
391	L5/6NP,Gluta,Neuronal
380	Sst,GABA,Neuronal
274	VLMC,VLMC,Non-Neuronal
266	Peri,Peri,Non-Neuronal
205	Vip,GABA,Neuronal
198	SMC,SMC,Non-Neuronal
185	L6b,Gluta,Neuronal
180	Lamp5,GABA,Neuronal
75	Sncg,GABA,Neuronal

10 clusters (only via 'cluster_class')
8881	Gluta
2001	Oligo
1803	Astro
1389	GABA
1294	other
1039	Endo
711	Micro
274	VLMC
266	Peri
198	SMC

## Extracting relevant information

In [51]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

# ==== Reformat relevant columns from 'cell_data.csv':
# 1 	Cell_ID
# 8 	cluster_subclass
# 9 	cluster_class
# 10	neuron_identity

# # Testing on one biorep
# biorep="$sample_dir/biorep1_techrep1"
# rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
# awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
#     if ($1 ~ /Cell_ID/){ print "#rep_id", "#" tolower($10), "#" tolower($9), "#" tolower($8), "#cell_id" }
# 	  else { gsub(/ /, "_", $8); print rep_id, tolower($10), tolower($9), tolower($8), $1 } } }' "$biorep/cell_data.csv" | sort -t ',' -k2,5 | head  | tr ',' '\t'


for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
	if [ -f "$biorep/cells.csv" ]; then
		continue
	fi
    basename "$biorep"
	if [ ! -f "$biorep/cell_data.csv" ] & [ -f "$biorep/cell_data.csv.gz" ]; then
		gunzip "$biorep/cell_data.csv.gz"
	fi

    rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
    awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
        if ($1 ~ /Cell_ID/){ print "#rep_id", "#" tolower($10), "#" tolower($9), "#" tolower($8), "#cell_id" }
        else { gsub(/ /, "_", $8); gsub(/\//, "-", $8); print rep_id, tolower($10), tolower($9), tolower($8), $1 } } }' "$biorep/cell_data.csv" | sort -t ',' -k2,5 > "$biorep/cells.csv"

	gzip "$biorep/cell_data.csv"
done

biorep3_techrep1
biorep1_techrep1
biorep2_techrep1
biorep3_techrep2

In [222]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

# ==== Reformat relevant columns from 'dna_spot_trace_core.csv':
# 2 	Trace_ID  (fovXX_cellXX_chrXX_chromatidXX)
# 3 	X
# 4 	Y
# 5 	Z
# 7 	Chrom_Start
# 8 	Chrom_End
# 9 	Chrom_order
# 10	Cell_ID

# # Testing on one biorep
# biorep="$sample_dir/biorep1_techrep1"
# rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
# awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
# 	tmp=$9","$7","$8","$3","$4","$5;
# 	if ($2 == "Trace_ID"){ molecule="#rep_id,#cell_id,#chrom,#hmlg"; tmp="#"gensub(/,/, ",#", "g", tolower(tmp)) }
# 	else { molecule=rep_id","$10","gensub(/.+_.+_(.+)_(.+)/, "\\1,\\2", "g", $2) };
# 	print molecule, tmp } }' "$biorep/dna_spot_trace_core.csv" | sort -t ',' -k2,2 -k3,3n -k4,4n -k5,5n | head | tr ',' '\t' | sed -r 's/(\.[0-9])[0-9]*/\1/g'


for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
	if [ -f "$biorep/dna_merfish.csv" ]; then
		continue
	fi
    basename "$biorep"
	if [ ! -f "$biorep/dna_spot_trace_core.csv" ] & [ -f "$biorep/dna_spot_trace_core.csv.gz" ]; then
		gunzip "$biorep/dna_spot_trace_core.csv.gz"
	fi

    rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
    awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
    	tmp=$9","$7","$8","$3","$4","$5;
    	if ($2 == "Trace_ID"){ molecule="#rep_id,#cell_id,#chrom,#hmlg"; tmp="#"gensub(/,/, ",#", "g", tolower(tmp)) }
    	else { molecule=rep_id","$10","gensub(/.+_.+_(.+)_(.+)/, "\\1,\\2", "g", $2) };
    	print molecule, tmp } }' "$biorep/dna_spot_trace_core.csv" | sort -t ',' -k2,2 -k3,3n -k4,4n -k5,5n > "$biorep/dna_merfish.csv"

	gzip "$biorep/dna_spot_trace_core.csv"
done

## Consolidating cell data across bioreps (excluding secondary tech reps per biorep)

In [52]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_techrep1"
cells_file="$allreps_dir/cells.csv"

# ==== Consolidate cells across bioreps (1st techrep only)

mkdir -p "$allreps_dir"
head -n 1 $(find "$sample_dir" -type f -path '*/biorep*_techrep1/cells.csv' | head -n 1) > "$cells_file" # Write header
grep -r "$sample_dir/"biorep*_techrep1/cells.csv -hve '^#' | sort -t ',' -k1,5 >> "$cells_file" # Write cells

In [53]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_techrep1"
cells_file="$allreps_dir/cells.csv"

# ==== Count cells & clusters across all bioreps

# Number of cells
echo -e $(grep -v '^["#]' "$cells_file" | wc -l)" cells (lines)"

# Number of clusters
nclust=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust" | wc -l)" clusters (only via 'cluster_subclass')"
nclust_trio=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 2-4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e $(echo -e "$nclust_trio" | wc -l)" clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):"
echo -e "$nclust_trio"

echo -e "\nNumber of (subclass-based) clusters with >= [cutoff] cells per cluster (ignoring 'other' cluster)"
for cutoff in 1000 2000; do
    echo -e "$nclust" | awk -vcutoff="$cutoff" 'BEGIN{ nlines=0; total=0 } \
        {if (($1 >= cutoff) && ($2 != "other")){nlines += 1; total += $1}} \
        END{ print nlines" clusters with >= "cutoff" cells per cluster, total cells="total }'
done

# Number of clusters (only via cluster_class)
nclust_class=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 3 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_class" | wc -l)" clusters (only via 'cluster_class')"
echo -e "$nclust_class"

47999 cells (lines)

22 clusters (only via 'cluster_subclass')
22 clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):
5433	non-neuronal,oligo,oligo
5348	neuronal,gluta,l6_ct
4833	non-neuronal,astro,astro
4721	neuronal,gluta,l2-3_it
3507	non-neuronal,endo,endo
2989	neuronal,gluta,l5_it
2945	neuronal,gluta,l4-5_it
2520	other,other,other
2366	neuronal,gluta,l6_it
2150	neuronal,gluta,l5_et
1953	non-neuronal,oligo,opc
1745	non-neuronal,micro,micro
1367	neuronal,gaba,pvalb
1001	neuronal,gaba,sst
955	neuronal,gluta,l6b
891	non-neuronal,peri,peri
791	neuronal,gluta,l5-6_np
716	non-neuronal,vlmc,vlmc
571	non-neuronal,smc,smc
500	neuronal,gaba,vip
496	neuronal,gaba,lamp5
201	neuronal,gaba,sncg

Number of (subclass-based) clusters with >= [cutoff] cells per cluster (ignoring 'other' cluster)
13 clusters with >= 1000 cells per cluster, total cells=40358
9 clusters with >= 2000 cells per cluster, total cells=34292

10 clusters (only via 'cluster_class')
22265	gluta
7386	oligo
4833	astro
3565	gaba
3507	endo
2520	other
1745	micro
891	peri
716	vlmc
571	smc

## Segregating DNA-MERFISH data per cluster (excluding 'other' cluster)

In [59]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
ncells_cutoff=2000

allreps_dir="$sample_dir/all_techrep1"
cells_file="$allreps_dir/cells.csv"

# ==== Get cells belonging to 'top' clusters (clusters with >= cutoff cells)
clusters_all=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
clusters_top=$( echo -e "$clusters_all" | awk -vcutoff="$ncells_cutoff" '{if (($1 >= cutoff) && ($2 != "other")) {print $2}}' )
nclust_top=$( echo -e "$clusters_top" | wc -l )

clusters_top_re="(^"$( echo -e "$clusters_top" | tr '\n' '|' | sed 's/|$//;s/|/$|^/g;s:/:.:g' )"$)"
cells_topclust_file="$allreps_dir/cells.top${nclust_top}clust.csv"
    
head -n 1 "$cells_file" | cut -d ',' -f 1,4,5 > "$cells_topclust_file"
awk -F',' 'BEGIN{OFS=","}{ if ($4 ~ /'"$clusters_top_re"'/){ print $1, $4, $5 } }' "$cells_file"  >> "$cells_topclust_file"


# ==== Label DNA MERFISH data from cells belonging to 'top' clusters (clusters with >= cutoff cells); discard data for other cells

dna_allreps_file="$allreps_dir/dna_merfish.top${nclust_top}clust.csv"

# # Make header for dna_allreps_file
# paste -d ',' \
#     <( echo "#cell_id" ) \
#     <( head -n 1 $(find "$sample_dir" -type f -path '*/biorep*_techrep1/dna_merfish.csv' | head -n 1 ) | sed 's/#cell_id,//' ) \
#     <( head -n 1 "$cells_topclust_file" | cut -d ',' -f 2    ) > "$dna_allreps_file"

# # Assign cluster label to DNA MERFISH data (for cells in the chosen clusters)
# for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep1' ); do
#     rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
#     awk -F ',' -v rep_id="$rep_id" '{ if (($1 == rep_id) || ($1 ~ /rep_id/)){ print $2 "," $3 } }' "$cells_topclust_file" | sort -t ',' -k 2b,2 | \
#         join -t ',' -j 2 --header --check-order "$biorep/dna_merfish.csv" - | grep -v '^#' >> "$dna_allreps_file"
# done

# Count number of cells matching one of the chosen clusters
echo "Total cells across all chosen clusters: "$( cut -d ',' -f 1 "$dna_allreps_file" | uniq | grep -v '^#' | wc -l )

# # ==== Segregate DNA MERFISH data by cluster

# # Make directories per cluster, write header for sorted dna_merfish file
# for cluster in $clusters_top; do
#     mkdir -p "$allreps_dir/cluster/$cluster"
#     head -n 1 "$dna_allreps_file" | cut -d ',' -f 1-10 > "$allreps_dir/cluster/$cluster/dna_merfish.$cluster.csv"
# done

# # Segregate DNA MERFISH data
# awk -F',' -v outdir="$allreps_dir" 'BEGIN{OFS=","}{ if ($1 !~ /^#/) \
#     { print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 >> outdir"/cluster/"$11"/dna_merfish."$11".csv" } }' "$dna_allreps_file"

# Count number of cells matching each of the chosen clusters
echo -e "\nCells per cluster:"
ncells_total=0
for cluster in $clusters_top; do
    ncells=$( cut -d ',' -f 1 "$allreps_dir/cluster/$cluster/dna_merfish.$cluster.csv" | uniq | grep -v '^#' | wc -l )
    echo "$cluster: $ncells cells"
    ncells_total=$(($ncells_total + $ncells)) 
done
echo "TOTAL: $ncells_total cells"

Total cells across all chosen clusters: 26266

Cells per cluster:
oligo: 4506 cells
l6_ct: 4263 cells
astro: 3654 cells
l2-3_it: 3376 cells
endo: 2785 cells
l5_it: 2133 cells
l4-5_it: 2361 cells
l6_it: 1857 cells
l5_et: 1331 cells
TOTAL: 26266 cells

In [296]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_techrep1"
clusters_dir="$allreps_dir/cluster"

cluster="astro"
cluster_file="$clusters_dir/$cluster/dna_merfish.$cluster.csv"

# All columns: 1=cell_id,  2=rep_id,  3=chrom,  4=trace_id,  5=chrom_order,  6=chrom_start,  7=chrom_end,  8=x,  9=y,  10=z

echo -e "\n\n==== QUESTION: Can a locus on a given 'chrom' be uniquely identified by either 'chrom_order', 'chrom_start', or 'chrom_end'? Or do you need some combo thereof?"

echo -e "\nInstances where a locus has the same start location but different end location (expected result=0):"
# Cols: #chrom,#chrom_start,#chrom_end
cut -d ',' -f 3,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1-2 | uniq -d | wc -l

echo -e "\nInstances where a locus has the same start/end location but different value for 'chrom_order' (expected result=0):"
# Cols: #chrom,#chrom_start,#chrom_end
cut -d ',' -f 3,5,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1-2 | uniq -d | wc -l

echo -e "\n\n==== CHARACTERIZING THE DATA"

echo -e "\nNumber of cells with data for each locus (on 1+ traces):"
# Cols: #cell_id,#chrom,#chrom_start,#chrom_end
cut -d ',' -f 1,3,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1 | uniq -c | awk '!/#/ {print $1}' | sort -k1,1nr | pymath

echo -e "\nNumber of loci associated with each traceID:\nnum_loci\ttraceID"
# Cols: #chrom,#trace_id,#chrom_start,#chrom_end
cut -d ',' -f 3,4,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 2 | sort | uniq -c | awk '!/#/ {print $1 "\t\t" $2}' | sort -k1,1nr

echo -e "\nNumber of cells associated with each traceID:\nnum_cells\ttraceID"
# Cols: #cell_id,#trace_id
cut -d ',' -f 1,4 "$cluster_file" | sort | uniq | cut -d ',' -f 2 | sort | uniq -c | awk '!/#/ {print $1 "\t\t" $2}' | sort -k1,1nr

echo -e "\n\n==== QUESTION: Are there ever cases where a single copy of a single homolog of a single chromosome is represented by 2+ traces?"
#echo "If (A) and (B) below are identical, then the answer is 'no', otherwise its a 'maybe'..."
echo "Gotta be honest, the below tests don't really answer this question"

echo -e "\n(A) Number of cell-locus pairs associated with each traceID:\nnum_cell-locus_pairs\ttraceID"
# Cols: #cell_id,#chrom,#trace_id,#chrom_start,#chrom_end
# 1. Get unique cell-locus-traces
# 2. Number of cell-locus pairs per trace_ID
cut -d ',' -f 1,3,4,6,7 "$cluster_file" | sort | uniq | \
    cut -d ',' -f 3 | sort | uniq -c | awk '!/#/ {print $1 "\t\t\t" $2}' | sort -k1,1nr 

echo -e "\n(B) Number copies of each cell-locus pair:\nnum_cell-locus_pairs\tnum_copies_of_given_pair"
# # Cols: #cell_id,#chrom,#trace_id,#chrom_start,#chrom_end
# 1. Get unique cell-locus-traces
# 2. Number of unique traces per cell-locus pair
# 3. How often we see the given number of unique traces per cell-locus pair
cut -d ',' -f 1,3,4,6,7 "$cluster_file" | sort | uniq | \
    cut -d ',' -f 1,2,4,5 | sort | uniq -c | \
    awk '!/#/ {print $1}' | sort | uniq -c | awk '!/#/ {print $1 "\t\t\t" $2}' | sort -k1,1nr  # TODO is this correct?

==== QUESTION: Can a locus on a given 'chrom' be uniquely identified by either 'chrom_order', 'chrom_start', or 'chrom_end'? Or do you need some combo thereof?

Instances where a locus has the same start location but different end location (expected result=0):
0

Instances where a locus has the same start/end location but different value for 'chrom_order' (expected result=0):
0


==== CHARACTERIZING THE DATA

Number of cells with data for each locus (on 1+ traces):
sum	1.64767e+06
mean	450.923
var	127864
med	352.5
min	24
max	1659
size	3654

Number of loci associated with each traceID:
num_loci	traceID
1981		1
1973		2
1901		3
710		4
128		5

Number of cells associated with each traceID:
num_cells	traceID
3654		1
1742		2
99		3
15		4
2		5


==== QUESTION: Are there ever cases where a single copy of a single homolog of a single chromosome is represented by 2+ traces?
Gotta be honest, the below tests don't really answer this question

(A) Number of cell-locus pairs associated with each traceID:
num_cell-locus_pairs	traceID
1486497			1
335557			2
9452			3
1122			4
128			5

(B) Number copies of each cell-locus pair:
num_cell-locus_pairs	num_copies_of_given_pair
1465881			1
178722			2
2863			3
188			4
18			5

## Mapping DNA-MERFISH traces to homologs

In [113]:
import os
import pandas as pd
import numpy as np

sample_dir = "~/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
clusters_dir = os.path.join(sample_dir, "all_techrep1", "cluster")

cluster = "astro"
cluster_file = os.path.join(clusters_dir, f"{cluster}/dna_merfish.{cluster}.csv")

In [107]:
df = pd.read_csv(cluster_file)
df.columns = [x.strip('#') for x in df.columns]

df.rename({'hmlg', 'trace_id'}, axis=1, inplace=True)

In [112]:
df

,cell_id,rep_id,chrom,trace_id,chrom_order,chrom_start,chrom_end,x,y,z
0,100267022990578563888527231462820232415,3.1,X,1,8,38748472,38759587,77.503165,134.552984,2.967085
1,100267022990578563888527231462820232415,3.1,X,1,9,41244470,41259864,78.239118,134.450069,2.917676
2,100267022990578563888527231462820232415,3.1,X,1,10,43740000,43757195,78.660050,134.469585,1.877078
3,100267022990578563888527231462820232415,3.1,X,1,12,51241370,51256067,78.686841,134.282074,2.027929
4,100267022990578563888527231462820232415,3.1,X,1,15,58747434,58759996,78.253423,133.644737,2.409235
...,...,...,...,...,...,...,...,...,...,...
1832751,99604416062120274931641911251862984356,2.1,17,1,52,73751388,73759983,71.962111,212.037365,2.676902
1832752,99604416062120274931641911251862984356,2.1,17,1,58,81246004,81259969,71.226009,211.825336,2.479248
1832753,99604416062120274931641911251862984356,2.1,17,1,61,84495097,84507590,71.126310,212.170183,2.135738
1832754,99604416062120274931641911251862984356,2.1,17,1,65,89346720,89359845,71.908791,211.205570,2.381380
1832755,99604416062120274931641911251862984356,2.1,17,1,67,90349499,90361278,71.901743,211.188607,2.830414

In [333]:
# is the 5th trace always the smallest, FOR EACH INDIVIDUAL CELL? such that I can drop the higher-numbered traces when >2 traces exist?
# ...NO!

def foo(df):
    if df.trace_id.max() == 1:
        return True
    return np.array_equal(df.sort_values('nloci', ascending=False).trace_id.values, np.arange(1, df.trace_id.max() + 1))

def bar(df):
    if df.trace_id.max() == 1:
        return None
    if np.array_equal(df.sort_values('nloci', ascending=False).trace_id.values, np.arange(1, df.trace_id.max() + 1)):
        return None
    return df.reset_index(drop=True)
    

tmp = df.groupby(['cell_id', 'trace_id']).size().reset_index()
tmp.rename({0: 'nloci'}, axis=1, inplace=True)

# tmp2 = tmp.groupby('cell_id').apply(foo, include_groups=False)
# print((~tmp2).sum())

tmp.groupby('cell_id').apply(bar, include_groups=False).reset_index(level=0).set_index(['cell_id', 'trace_id'])

                                                  nloci
cell_id                                 trace_id
135569624016926935223191268945163650316 1           420
                                        2            49
                                        3            61
166182041445444368394872966466019634181 1            49
                                        2            52
265530322711175505052747986601265017674 1           174
                                        2            45
                                        3            47
293306416906937544042439740226453432537 1            31
                                        2            35
8055401355195744077875080897803174798   1           666
                                        2            34
                                        3            38

In [294]:
def count_occurances_of_locus(df, n_traces):
    s = pd.Series({'ncopies': len(df), 'ncells': len(df.cell_id.drop_duplicates())})
    for i in range(1, n_traces + 1):
        s[f'ncells_{i}copies'] = (df.groupby('cell_id').size() == i).sum()
    return s

def add_missing_loci(df):
    if len(df) == df.chrom_order.max() + 1 - df.chrom_order.min():
        return df
    bins_all = np.arange(df.chrom_order.min(), df.chrom_order.max() + 1, dtype=int)
    is_missing = np.isin(bins_all, df.chrom_order.values, assume_unique=True, invert=True)

    df_missing = pd.DataFrame()
    df_missing['chrom_order'] = bins_all[is_missing]
    df_full = pd.concat([df, df_missing]).sort_values('chrom_order').fillna(0).reset_index(drop=True)
    for col in df.columns:
        df_full[col] = df_full[col].astype(int)
    return df_full


# per_locus = df.groupby(['chrom', 'chrom_order']).size().reset_index()
# per_locus.rename({0: 'ncopies'}, axis=1, inplace=True)
# # per_locus = per_locus.drop(index=[1, 3]).reset_index(drop=True) # FIXME remove, just for testing
# per_locus = per_locus.groupby('chrom').apply(add_missing_loci, include_groups=False).reset_index(level=0)
# per_locus['ncopies'].describe()

n_traces = df.trace_id.max()
per_locus = df.groupby(['chrom', 'chrom_order']).apply(count_occurances_of_locus, include_groups=False, n_traces=n_traces).reset_index()
for i in range(1, n_traces + 1):
    print(i, per_locus[f'ncells_{i}copies'].sum())
    if per_locus[f'ncells_{i}copies'].sum() == 0:
        per_locus.drop(f'ncells_{i}copies', axis=1)
per_locus = per_locus.groupby('chrom').apply(add_missing_loci, include_groups=False).reset_index(level=0)
per_locus

1 1465881
2 178722
3 2863
4 188
5 18

,chrom,chrom_order,ncopies,ncells,ncells_1copies,ncells_2copies,ncells_3copies,ncells_4copies,ncells_5copies
0,1,0,1133,1001,872,126,3,0,0
1,1,1,840,758,677,80,1,0,0
2,1,2,616,577,538,39,0,0,0
3,1,3,956,853,751,101,1,0,0
4,1,4,791,733,675,58,0,0,0
...,...,...,...,...,...,...,...,...,...
1976,X,59,388,388,388,0,0,0,0
1977,X,60,423,420,417,3,0,0,0
1978,X,61,416,413,410,3,0,0,0
1979,X,62,401,400,399,1,0,0,0
1980,X,63,560,557,554,3,0,0,0

In [277]:
per_locus['ncopies'].describe()

count    1981.000000
mean      925.167087
std       222.108784
min        64.000000
25%       805.000000
50%       932.000000
75%      1065.000000
max      1896.000000
Name: ncopies, dtype: float64

In [273]:
per_locus['ncells'].describe()

count    1981.000000
mean      831.737506
std       181.222579
min        63.000000
25%       735.000000
50%       841.000000
75%       951.000000
max      1555.000000
Name: ncells, dtype: float64

In [278]:
per_locus['ncells_min2copies'].describe()

count    1981.000000
mean       91.767289
std        41.751935
min         0.000000
25%        66.000000
50%        89.000000
75%       116.000000
max       386.000000
Name: ncells_min2copies, dtype: float64

- QUESTION: Are there ever cases where a single copy of a single homolog of a single chromosome is represented by 2+ traces?
- WHich traces to drop?